SERVICE_NAME = 'novapulse'


COMMON_TOKEN = ['WSOL',
          'GgsS',
          'USDT',
          'JLP',
          'WBTC',
          'PENGU',
          'mSOL',
          'WETH',
          'swarms',
          'Fartcoin ',
          'bluwhaleAI',
          'USDS',
          'JitoSOL',
          'AVA',
          'ALCH',
          'ME',
          'cbBTC',
          'SPX',
          'arc',
          'RAY',
          'GRIFFAIN',
          'SONIC',
          'CLOUD',
          'CHILLGUY',
          'SUIDEPIN',
          'POPCAT',
          'DRIFT',
          'InfinityAI',
          'AIPUMP',
          'MLG',
          'pippin',
          'GRIFT',
          'BUILD',
          'Bonk',
          'FREGO',
          '8008',
          'JUP',
          'GOAT',
          'USDC',
          'LLM',
          'Butthole',
          '$MYRO',
          'TSOTCHKE',
          'JTO',
          'JupSOL',
          'KMNO',
          'TNSR',
          'USDC',
          'USDC',
          'HNT',
          'KWAII']
